url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: AlvesTur
email: alvesturturismo@hotmail.com
description: "AlvesTur."
logo: <img src="{{site.url}}/{{site.baseurl}}/img/logos/alvestur.png" class="img-responsive" width="20%" height="100%">
address: R. Moacir Alençar - Santos Dumont, Maceió - AL
phone: (82) 98811-9535 (82) 99302-8539

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/alvestur/
  - title: instagram 
    url: https://www.instagram.com/alvesturmcz_/
  - title: youtube
    url: https://www.youtube.com/channel/UCNMSdYJ4MwYhpJvKiubd-Dw

# Build settings
markdown: kramdown
permalink: pretty